import copy
import time
from types import SimpleNamespace

import pytest

from h3_slides.models import Generation, ProjectInput, SlideContent
from h3_slides.storage import Store
from h3_slides.worker import Worker
from h3_slides.web_research import source_citations


TEXT = ("Il Terrore fu una fase della Rivoluzione francese in cui il governo rivoluzionario "
        "adottò misure eccezionali. Il conflitto interno e la guerra aumentarono le tensioni "
        "politiche, favorendo la repressione degli oppositori e il ricorso ai tribunali rivoluzionari.")
MATH_TEXT = ("La funzione inversa associa a ogni numero reale diverso da zero il suo reciproco. "
             "Il dominio esclude quindi lo zero e comprende valori positivi e negativi. "
             r"\(y=\frac{1}{x}\) con \(x\ne0\)")


def research_bundle():
    return {"provider": "Fixture", "query": "Rivoluzione francese", "created_at": time.time(),
            "sources": [{"id": "W1", "title": "Rivoluzione francese",
                         "url": "https://it.wikipedia.org/wiki/Rivoluzione_francese",
                         "text": TEXT, "retrieved_at": time.time()}],
            "warnings": [], "cache_used": False}


@pytest.fixture
def store(tmp_path):
    result = Store(tmp_path)
    yield result
    result.db.close()


@pytest.mark.asyncio
@pytest.mark.parametrize("mode", ["local", "remote"])
@pytest.mark.parametrize("scenario", ["missing", "missing_math", "unknown_block", "formatted", "unrecoverable", "new_failure"])
async def test_web_citation_recovery_keeps_content_and_never_invents_sources(store, mode, scenario):
    project = store.create(ProjectInput(title="Rivoluzione francese", prompt="Spiega il Terrore",
        count=1, text_density="complete", web_enabled=True,
        web_query="Rivoluzione francese").model_dump())
    expected_text = MATH_TEXT if scenario == "missing_math" else TEXT
    original = SlideContent(title="Il Terrore", blocks=[{"heading": "Fase politica", "text": expected_text,
                                                        "source": "W1 · Rivoluzione francese"}],
                            sources=source_citations(["W1"], research_bundle(), [])).model_dump()
    if scenario != "new_failure":
        project["slides"] = [{"id": "existing", "revision": 4, "status": "ready",
                              "content": original, "purpose": "Spiega il Terrore", "block_count": 1}]
        store.save_project(project)
    prompts, schemas, searches = [], [], []

    class Research:
        async def collect(self, pid, **kwargs):
            searches.append(kwargs)
            return research_bundle()

    class LLM:
        def __init__(self, provider, *_):
            assert provider.mode == mode

        async def prepare(self):
            pass

        async def json(self, prompt, schema=None, **kwargs):
            if "Proponi esattamente" in prompt:
                return {"slides": [{"title": "Il Terrore", "purpose": "Spiega il Terrore",
                                    "block_count": 1, "layout": "content"}]}
            prompts.append(prompt)
            schemas.append(copy.deepcopy(schema))
            result = copy.deepcopy(original)
            if scenario == "formatted":
                return result  # Exactly the public format generated by the application.
            if scenario in {"unrecoverable", "new_failure"}:
                result["sources"], result["blocks"][0]["source"] = [], "https://invented.example/facts"
            elif len(prompts) == 1:
                result["sources"] = [] if scenario in {"missing", "missing_math"} else ["W1"]
                result["blocks"][0]["source"] = "" if scenario in {"missing", "missing_math"} else "W99"
            else:
                assert "CORREGGI LE CITAZIONI" in prompt
                assert "Non assegnare una fonte arbitraria" in prompt
                assert "BUDGET PER PARAGRAFO RICALCOLATO" not in prompt
                result["sources"], result["blocks"][0]["source"] = ["W1"], "W1"
            return result

    worker = Worker(store, SimpleNamespace())
    worker.researcher, worker.clients = Research(), LLM
    request = Generation(provider={"mode": mode, "model": "fixture", "remote_consent": True,
                                    "base_url": "https://provider.example/v1"},
                         prompt=project["prompt"], count=1, web_consent=True,
                         regenerate_all=scenario != "new_failure")
    job = worker.submit(project["id"], request)
    await worker.tasks[job["id"]]
    state, saved = store.job(job["id"]), store.project(project["id"])
    slide = saved["slides"][0]
    assert len(searches) == 1
    assert all("CATALOGO CITAZIONI ATTUALE" in prompt for prompt in prompts)
    assert all(schemas[0] == schema for schema in schemas)
    messages = [event["message"] for event in state["events"]]
    if scenario == "new_failure":
        assert state["status"] == "failed"
        assert len(prompts) == 3
        assert slide["revision"] == 0 and not slide["content"]["sources"]
        assert "Citazioni mancanti" in state["error"]
    elif scenario == "unrecoverable":
        assert slide["content"] == original and slide["revision"] == 4
        assert len(prompts) == 3 and slide["status"] == "ready"
        assert any("versione precedente conservata" in message for message in messages)
    else:
        assert state["status"] == "completed", messages
        assert len(prompts) == (1 if scenario == "formatted" else 2)
        assert slide["revision"] == 5
        assert slide["content"]["blocks"][0]["text"] == expected_text
        assert slide["content"]["blocks"][0]["source"] == "W1 · Rivoluzione francese"
        assert slide["content"]["sources"] == original["sources"]
        if scenario != "formatted":
            assert any("Correzione delle citazioni" in message for message in messages)
        assert not any("Correzione del testo" in message for message in messages)
        assert not any("Testo adattato" in message for message in messages)
