import assert from 'node:assert/strict';
import {chromium} from 'playwright-chromium';
const [url,pid]=process.argv.slice(2);
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];
page.on('pageerror',error=>errors.push(error.message));
try{
  await page.goto(url);
  await page.locator('#project-list option[value="'+pid+'"]').waitFor({state:'attached'});
  await page.locator('#project-list').selectOption(pid);
  await page.locator('.slide-card').waitFor();
  await page.locator('#open-library').click();
  await page.locator('#library').waitFor();
  assert.equal(new URL(page.url()).pathname,'/library');
  assert.equal(await page.locator('.project-card[data-project="'+pid+'"]').count(),1);
  await page.locator('.project-card[data-project="'+pid+'"] [data-open-project]').click();
  await page.locator('.slide-card').waitFor();
  assert.equal(new URL(page.url()).pathname,'/');
  await page.locator('#toggle-sidebar').click();
  assert.equal(await page.locator('body').evaluate(body=>body.classList.contains('sidebar-collapsed')),true);
  await page.reload();
  assert.equal(await page.locator('body').evaluate(body=>body.classList.contains('sidebar-collapsed')),true);
  await page.locator('#toggle-sidebar').click();
  assert.equal(await page.locator('.slide-card').first().locator('.heading').getAttribute('draggable'),'true');
  const headingMoved=page.waitForResponse(r=>r.url().includes('/slides/')&&r.request().method()==='PATCH');
  const headingBox=await page.locator('.slide-card').first().locator('.heading').boundingBox();
  const footerBox=await page.locator('.slide-card').first().locator('.footer').boundingBox();
  await page.mouse.move(headingBox.x+headingBox.width/2,headingBox.y+headingBox.height/2);
  await page.mouse.down();
  await page.mouse.move(footerBox.x+footerBox.width/2,footerBox.y+footerBox.height/2,{steps:12});
  await page.mouse.up();
  assert.equal((await headingMoved).status(),200);
  const boxes=page.locator('.slide-card').first().locator('.prose-box');
  if(await boxes.count()>1){
    const source=page.locator('.slide-card').first().locator('[data-block-index="0"]');
    const target=page.locator('.slide-card').first().locator('[data-block-index="1"]');
    const sourceText=await source.locator('p').textContent();
    const transfer=await page.evaluateHandle(()=>new DataTransfer());
    await source.dispatchEvent('dragstart',{dataTransfer:transfer});
    await page.waitForTimeout(50);
    const targetBox=await target.boundingBox();
    await target.dispatchEvent('dragover',{dataTransfer:transfer,
      clientX:targetBox.x+targetBox.width/2,clientY:targetBox.y+targetBox.height-2});
    assert.equal(await page.locator('.item-drag-placeholder').count(),1);
    assert.ok((await page.locator('.item-drag-placeholder').textContent()).includes(sourceText));
    assert.equal(await source.evaluate(item=>item.classList.contains('drag-preview-source')),true);
    assert.match(await page.locator('.anchor-indicator').first().textContent(),/anteprima live/);
    const reordered=page.waitForResponse(r=>r.url().includes('/slides/')&&r.request().method()==='PATCH');
    await target.dispatchEvent('drop',{dataTransfer:transfer,
      clientX:targetBox.x+targetBox.width/2,clientY:targetBox.y+targetBox.height-2});
    assert.equal((await reordered).status(),200);
    assert.equal(await page.locator('.item-drag-placeholder').count(),0);
  }
  await page.locator('[data-action="arrange"]').first().click();
  assert.equal(await page.locator('.slide-card').first().evaluate(card=>card.classList.contains('layout-editing')),true);
  await page.locator('[data-action="arrange"]').first().click();
  const blockCount=await page.locator('.slide-card').first().locator('.prose-box').count();
  const blockAdded=page.waitForResponse(r=>r.url().includes('/slides/')&&r.request().method()==='PATCH');
  await page.locator('[data-action="add-text"]').first().click();
  assert.equal((await blockAdded).status(),200);
  assert.equal(await page.locator('.slide-card').first().locator('.prose-box').count(),blockCount+1);
  await page.getByRole('button',{name:'Modifica',exact:true}).click();
  await page.locator('#edit-title').fill('Modifica verificata nel browser');
  await page.getByRole('button',{name:'Salva modifica',exact:true}).click();
  await page.locator('#editor').waitFor({state:'hidden'});
  await page.reload();
  await page.getByRole('heading',{name:'Modifica verificata nel browser'}).waitFor();
  const paragraphs=await page.locator('.prose-box p').allTextContents();
  let savedLayout=page.waitForResponse(r=>r.url().includes('/slides/')&&r.request().method()==='PATCH');
  await page.locator('[data-slide-layout]').selectOption('comparison');
  assert.equal((await savedLayout).status(),200);
  await page.reload();
  await page.locator('[data-slide-layout]').waitFor();
  assert.equal(await page.locator('[data-slide-layout]').inputValue(),'comparison');
  assert.deepEqual(await page.locator('.prose-box p').allTextContents(),paragraphs);
  savedLayout=page.waitForResponse(r=>r.url().includes('/slides/')&&r.request().method()==='PATCH');
  await page.locator('[data-action="recompose"]').click();
  assert.equal((await savedLayout).status(),200);
  await page.reload();
  await page.locator('.prose-box p').first().waitFor();
  assert.deepEqual(await page.locator('.prose-box p').allTextContents(),paragraphs);
  await page.locator('#prompt').fill('Una modifica al brief ancora non salvata');
  await page.waitForTimeout(1800);
  assert.equal(await page.locator('#prompt').inputValue(),'Una modifica al brief ancora non salvata');
  await page.locator('#open-admin').click();
  await page.locator('#provider').selectOption('remote');
  assert.ok(await page.locator('#remote-fields').isVisible());
  await page.locator('#provider').selectOption('local');
  assert.ok(await page.locator('#local-fields').isVisible());
  await page.locator('#close-admin').click();
  assert.equal(await page.locator('.slide-card').count(),1);
  await page.locator('#template').selectOption('steps');
  await page.locator('#font').selectOption('Georgia');
  await page.locator('#source-images').uncheck();
  const styleSaved=page.waitForResponse(r=>r.url().includes('/api/projects/'+pid)&&r.request().method()==='PATCH');
  await page.locator('#save-project').click();
  await styleSaved;
  await page.reload();
  await page.locator('.slide-frame').waitFor();
  assert.equal(await page.locator('#template').inputValue(),'steps');
  assert.equal(await page.locator('.prose-box').count(),blockCount+1);
  await page.locator('[data-edit-field="block-text"]').first().dblclick();
  const paragraph='Questo paragrafo modificato nel browser resta dentro il box e viene conservato anche dopo il ricaricamento della pagina.';
  await page.locator('[contenteditable]').fill(paragraph);
  const paragraphSaved=page.waitForResponse(r=>r.url().includes('/slides/')&&r.request().method()==='PATCH');
  await page.locator('[contenteditable]').press('Enter');
  assert.equal((await paragraphSaved).status(),200);
  await page.reload();
  await page.getByText(paragraph,{exact:true}).waitFor();
  assert.equal(await page.locator('#font').inputValue(),'Georgia');
  assert.equal(await page.locator('#source-images').isChecked(),false);
  await page.locator('h1[data-edit-field="title"]').dblclick();
  await page.locator('[contenteditable]').fill('Titolo inline verificato');
  const inlineSaved=page.waitForResponse(r=>r.url().includes('/slides/')&&r.request().method()==='PATCH');
  await page.locator('[contenteditable]').press('Enter');
  await inlineSaved;
  await page.locator('#open-admin').click();
  await page.locator('#admin').waitFor();
  await page.locator('[data-setting="inference.temperature"]').fill('0.44');
  const saved=page.waitForResponse(r=>r.url().includes('/api/admin/llm')&&r.request().method()==='POST');
  await page.getByRole('button',{name:'Salva profilo',exact:true}).click();
  assert.equal((await saved).status(),200);
  await page.locator('#close-admin').click();
  await page.locator('#open-admin').click();
  assert.equal(await page.locator('[data-setting="inference.temperature"]').inputValue(),'0.44');
  await page.locator('#close-admin').click();
  await page.reload();
  await page.getByRole('heading',{name:'Titolo inline verificato',exact:true}).waitFor();
  await page.getByText('Creatore di temi',{exact:true}).click();
  await page.locator('#theme-presets option', {hasText:'Notte'}).waitFor({state:'attached'});
  await page.locator('#theme-presets').selectOption({label:'Notte · blu e corallo'});
  assert.equal(await page.locator('#background-color').inputValue(),'#111d35');
  assert.equal(await page.locator('.prose-box').first().evaluate(e=>getComputedStyle(e).color),'rgb(255, 255, 255)');
  await page.locator('[data-theme-number="body_size"]').fill('21');
  assert.equal(await page.locator('.prose-box p').first().evaluate(e=>getComputedStyle(e).fontSize),'21px');
  await page.locator('[data-theme-auto="text_color"]').uncheck();
  await page.locator('[data-theme-color="text_color"]').fill('#111d35');
  assert.match(await page.locator('#theme-contrast').textContent(),/poco contrasto/);
  await page.locator('[data-theme-auto="text_color"]').check();
  await page.locator('#theme-name').fill('Tema test browser');
  const themeSaved=page.waitForResponse(r=>r.url().endsWith('/api/themes')&&r.request().method()==='POST');
  await page.locator('#save-theme').click();
  assert.equal((await themeSaved).status(),200);
  const briefSaved=page.waitForResponse(r=>r.url().endsWith('/api/projects/'+pid)&&r.request().method()==='PATCH');
  await page.locator('#save-project').click();
  assert.equal((await briefSaved).status(),200);
  await page.reload();
  await page.locator('.prose-box').first().waitFor();
  assert.equal(await page.locator('#background-color').inputValue(),'#111d35');
  assert.equal(await page.locator('[data-theme-number="body_size"]').inputValue(),'21');
  await page.locator('#theme-presets option').filter({hasText:'Tema test browser'}).waitFor({state:'attached'});
  await page.locator('#web-enabled').check();
  await page.locator('#web-query').fill('Query visibile prima del consenso');
  await page.locator('#web-consent').check();
  await page.locator('#web-query').fill('Query cambiata');
  assert.equal(await page.locator('#web-consent').isChecked(),false);
  await page.reload();
  await page.locator('.slide-card').waitFor();
  assert.equal(await page.locator('#web-enabled').isChecked(),false);
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
  assert.equal(overflow,false);
  assert.deepEqual(errors,[]);
  console.log('Browser: editor, persistenza, temi, contrasto, consenso web e provider verificati.');
}finally{await browser.close()}
